package smv

// all supported operators
// shared by SMV, LTL, CTL related stuffs
sealed abstract class Op(val name: String)
case object Nop extends Op("")
case object Not extends Op("!")
case object And extends Op("&")
case object Or extends Op("|")
case object Xor extends Op("xor")
case object Xnor extends Op("xnor")
case object Imply extends Op("->")
case object Equiv extends Op("<->")
case object Equal extends Op("=")
case object NotEqual extends Op("!=")
case object Lt extends Op("<")
case object Gt extends Op(">")
case object Le extends Op("<=")
case object Ge extends Op(">=")
case object Neg extends Op("-")
case object Add extends Op("+")
case object Sub extends Op("-")
case object Mul extends Op("*")
case object Div extends Op("/")
case object Mod extends Op("mod")
case object Shr extends Op(">>")
case object Shl extends Op("<<")
case object Cat extends Op("::")
case object Next extends Op("X")
case object Global extends Op("G")
case object Final extends Op("F")
case object Until extends Op("U")
case object ENext extends Op("EX")
case object EGlobal extends Op("EG")
case object EFinal extends Op("EF")
case object EUntil extends Op("EU")
case object ANext extends Op("AX")
case object AGlobal extends Op("AG")
case object AFinal extends Op("AF")
case object AUntil extends Op("AU")
